//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamVoyage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int IdBooking { get; set; }
        public int IdUser { get; set; }
        public int IdDestination { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int NumberOfPeople { get; set; }
        public decimal TotalPrice { get; set; }
        public string Trangthai { get; set; }
        public string Note { get; set; }
    }
}
