//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamVoyage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public Destination()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int IdDestination { get; set; }
        public string NameDestination { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
