//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietNamVoyage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int IdReview { get; set; }
        public int IdUser { get; set; }
        public int IdDestination { get; set; }
        public string Review1 { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual User User { get; set; }
    }
}
